Repository TigardHighGDC/Augmentation, pull requests merged in 2022-12, with the labels that each got.

#10 Fix for `UserSettings/` ignore
  .gitignore
Labels: bug

#11 Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#13 Player Movement
  Assets/Prefabs.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
  Assets/Scripts.meta
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerMovement.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/AudioManager.asset
  ProjectSettings/ClusterInputManager.asset
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/MemorySettings.asset
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/NetworkManager.asset
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/PresetManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/QualitySettings.asset
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
  ProjectSettings/TimeManager.asset
  ProjectSettings/UnityConnectSettings.asset
  ProjectSettings/VFXManager.asset
  ProjectSettings/VersionControlSettings.asset
  ProjectSettings/XRSettings.asset
  ProjectSettings/boot.config
Labels: feature
