Repository TigardHighGDC/Augmentation, pull requests merged in 2023-03, with the labels that each got.

#94 Sprint 4 changelog
  Docs/ChangeLog.md
Labels: documentation

#96 Unity update `2021.3.20f1`
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: high priority, unity

#98 Comments weren't uploaded to AIPhysics
  Assets/Scripts/Enemies/AIPhysics.cs
Labels: documentation

#97 EY Enemy
  Assets/Art/Enemies/EY.meta
  Assets/Art/Enemies/EY/Untitled523_20230221184329.png
  Assets/Art/Enemies/EY/Untitled523_20230221184329.png.meta
  Assets/Art/Enemies/EY/Untitled523_20230221184339.png
  Assets/Art/Enemies/EY/Untitled523_20230221184339.png.meta
  Assets/Art/Enemies/EY/Untitled523_20230221184341.png
  Assets/Art/Enemies/EY/Untitled523_20230221184341.png.meta
  Assets/Prefabs/A-StarGrid.prefab
  Assets/Prefabs/EY Position.prefab
  Assets/Prefabs/EY Position.prefab.meta
  Assets/Prefabs/EnemyBullet.prefab
  Assets/Prefabs/EnemyBullet.prefab.meta
  Assets/Prefabs/LaptopGoon.prefab
  Assets/Scenes/Example Room.unity
  Assets/Scripts/Enemies/AIPhysics.cs
  Assets/Scripts/Enemies/EY.meta
  Assets/Scripts/Enemies/EY/EY.asset
  Assets/Scripts/Enemies/EY/EY.asset.meta
  Assets/Scripts/Enemies/EY/EY_AI.cs
  Assets/Scripts/Enemies/EY/EY_AI.cs.meta
  Assets/Scripts/Enemies/EY/EyeTracking.cs
  Assets/Scripts/Enemies/EY/EyeTracking.cs.meta
  Assets/Scripts/Enemies/EY/LaserLine.cs
  Assets/Scripts/Enemies/EY/LaserLine.cs.meta
  Assets/Scripts/Enemies/EnemyAI.cs
  Assets/Scripts/Enemies/EnemyAI.cs.meta
  Assets/Scripts/Enemies/EnemyProjectile.meta
  Assets/Scripts/Enemies/EnemyProjectile/EnemyBullet.cs
  Assets/Scripts/Enemies/EnemyProjectile/EnemyBullet.cs.meta
  Assets/Scripts/Enemies/EnemyProjectile/EnemyProjectileData.cs
  Assets/Scripts/Enemies/EnemyProjectile/EnemyProjectileData.cs.meta
  Assets/Scripts/Enemies/LaptopGoon/LaptopGoon.asset
  Assets/Scripts/Enemies/LaptopGoon/LaptopGoon.asset.meta
  Assets/Scripts/Enemies/LaptopGoon/LaptopGoonAI.cs
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Universal Camera.prefab
Labels: feature

#99 Hackerman Created
  Assets/Art/Enemies/hackermanSampleEdit.png
  Assets/Art/Enemies/hackermanSampleEdit.png.meta
  Assets/Prefabs/Hackerman.prefab
  Assets/Prefabs/Hackerman.prefab.meta
  Assets/Scenes/Example Room.unity
  Assets/Scripts/Enemies/EnemyDealDamage.cs
  Assets/Scripts/Enemies/Hackerman.meta
  Assets/Scripts/Enemies/Hackerman/Hackerman.asset
  Assets/Scripts/Enemies/Hackerman/Hackerman.asset.meta
  Assets/Scripts/Enemies/Hackerman/HackermanAI.cs
  Assets/Scripts/Enemies/Hackerman/HackermanAI.cs.meta
  Assets/Scripts/Enemies/Hackerman/MomentumAI.cs
  Assets/Scripts/Enemies/Hackerman/MomentumAI.cs.meta
Labels: feature

#100 Player Image Update
  Assets/Art/Player.png
  Assets/Art/Player.png.meta
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Player/PlayerMovement.cs
Labels: art

#101 Bug enemy
  Assets/Animation.meta
  Assets/Animation/Bug.meta
  Assets/Animation/Bug/Bug1.controller
  Assets/Animation/Bug/Bug1.controller.meta
  Assets/Animation/Bug/BugMoving.anim
  Assets/Animation/Bug/BugMoving.anim.meta
  Assets/Art/Enemies/Bug.meta
  Assets/Art/Enemies/Bug/Bug1.png
  Assets/Art/Enemies/Bug/Bug1.png.meta
  Assets/Art/Enemies/Bug/Bug2.png
  Assets/Art/Enemies/Bug/Bug2.png.meta
  Assets/Prefabs/Bug.prefab
  Assets/Prefabs/Bug.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Enemies/Bug.meta
  Assets/Scripts/Enemies/Bug/BugAI.cs
  Assets/Scripts/Enemies/Bug/BugAI.cs.meta
Labels: feature

#104 Async scene loader fix
  Assets/Scripts/Environment/SceneLoader.cs
Labels: bug

#114 Bug update
  Assets/Animation/Bug.anim
  Assets/Animation/Bug.anim.meta
  Assets/Animation/Bug/BugMoving.anim.meta
  Assets/Animation/Bug1.controller
  Assets/Animation/Bug1.controller.meta
  Assets/Art/Enemies/Bug/Bug1.png
  Assets/Art/Enemies/Bug/Bug1.png.meta
  Assets/Art/Enemies/Bug/Bug2.png
  Assets/Art/Enemies/Bug/Bug2.png.meta
  Assets/Prefabs/Bug.prefab
  Assets/Prefabs/Player 1.prefab
  Assets/Scenes/Example Room.unity
  Assets/Scripts/Enemies/Bug/BugAI.cs
  Assets/Scripts/Enemies/EnemyAI.cs
  Assets/Scripts/Enemies/EnemyDealDamage.cs
Labels: enhancement

#107 Weapon Inventory
  Assets/Scenes/Example Room 2.unity
  Assets/Scenes/Example Room 2.unity.meta
  Assets/Scripts/Player/WeaponInventory.cs
  Assets/Scripts/Player/WeaponInventory.cs.meta
  Assets/Scripts/Util.meta
  Assets/Scripts/Util/Assert.cs
  Assets/Scripts/Util/Assert.cs.meta
Labels: feature

#119 Update `Bug.prefab`
  Assets/Prefabs/Bug.prefab
Labels: bug

#120 Sniper quick change
  Assets/Scripts/Weapons/Data/AssaultRifle.asset
  Assets/Scripts/Weapons/Data/BigBoy.asset
  Assets/Scripts/Weapons/Data/Pistol.asset
  Assets/Scripts/Weapons/Data/Shotgun.asset
  Assets/Scripts/Weapons/Data/Sniper.asset
  Assets/Scripts/Weapons/Data/WeaponData.cs
  Assets/Scripts/Weapons/ProjectileGun/Gun.cs
Labels: enhancement

#125 Corruption effects
  Assets/Scenes/CorruptionSoundTest.unity
  Assets/Scenes/CorruptionSoundTest.unity.meta
  Assets/Scripts/AudioManipulation.cs
  Assets/Scripts/DebugTools.meta
  Assets/Scripts/DebugTools/CorruptionSet.cs
  Assets/Scripts/DebugTools/CorruptionSet.cs.meta
  Assets/Scripts/Player/CorruptionLevel.cs
  Assets/Scripts/UI/CorruptionEye.cs
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
  Assets/Scripts/Weapons/ProjectileGun/Gun.cs
Labels: bug, feature
