Repository TigardHighGDC/Augmentation, pull requests merged in 2023-04, with the labels that each got.

#127 Bullet Pierce
  Assets/Scripts/Weapons/Data/AssaultRifle.asset
  Assets/Scripts/Weapons/Data/Pistol.asset
  Assets/Scripts/Weapons/Data/Shotgun.asset
  Assets/Scripts/Weapons/Data/Sniper.asset
  Assets/Scripts/Weapons/Data/WeaponData.cs
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Labels: enhancement

#130 Wall Fix
  Assets/Prefabs/Bug.prefab
  Assets/Scenes/Example Room 2.unity
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
  ProjectSettings/TagManager.asset
Labels: enhancement

#132 Added mixer to audio
  Assets/Audio.meta
  Assets/Audio/Mixer.meta
  Assets/Audio/Mixer/Master.mixer
  Assets/Audio/Mixer/Master.mixer.meta
  Assets/Audio/SoundFTX.meta
  Assets/Audio/SoundFTX/GunAudio.meta
  Assets/Audio/SoundFTX/GunAudio/AssaultRifle.meta
  Assets/Audio/SoundFTX/GunAudio/AssaultRifle/!AR Shot.mp3
  Assets/Audio/SoundFTX/GunAudio/AssaultRifle/!AR Shot.mp3.meta
  Assets/Audio/SoundFTX/GunAudio/BigBoy.meta
  Assets/Audio/SoundFTX/GunAudio/BigBoy/shotgun 02.mp3
  Assets/Audio/SoundFTX/GunAudio/BigBoy/shotgun 02.mp3.meta
  Assets/Audio/SoundFTX/GunAudio/Pistol.meta
  Assets/Audio/SoundFTX/GunAudio/Pistol/gun reload 01.mp3
  Assets/Audio/SoundFTX/GunAudio/Pistol/gun reload 01.mp3.meta
  Assets/Audio/SoundFTX/GunAudio/Pistol/pistol_shot.mp3
  Assets/Audio/SoundFTX/GunAudio/Pistol/pistol_shot.mp3.meta
  Assets/Audio/SoundFTX/GunAudio/Shotgun.meta
  Assets/Audio/SoundFTX/GunAudio/Shotgun/!shotgun mag reload (1.5sec).mp3
  Assets/Audio/SoundFTX/GunAudio/Shotgun/!shotgun mag reload (1.5sec).mp3.meta
  Assets/Audio/SoundFTX/GunAudio/Shotgun/shotgun 03.mp3
  Assets/Audio/SoundFTX/GunAudio/Shotgun/shotgun 03.mp3.meta
  Assets/Audio/SoundFTX/GunAudio/Sniper.meta
  Assets/Audio/SoundFTX/GunAudio/Sniper/!Sniper Reload 01 (2sec).mp3
  Assets/Audio/SoundFTX/GunAudio/Sniper/!Sniper Reload 01 (2sec).mp3.meta
  Assets/Audio/SoundFTX/GunAudio/Sniper/sniper 01.mp3
  Assets/Audio/SoundFTX/GunAudio/Sniper/sniper 01.mp3.meta
  Assets/Prefabs/Player 1.prefab
  Assets/Scenes/Example Room 2.unity
Labels: feature

#140 Prefab Quick Fix
  Assets/Prefabs/LaptopGoon.prefab
Labels: bug, high priority

#152 Prefab Duplicate Deleted
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
Labels: bug

#156 Item Handling
  Assets/Scripts/Item.meta
  Assets/Scripts/Item/ItemHandling.cs
  Assets/Scripts/Item/ItemHandling.cs.meta
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Labels: feature

#157 Basic level setup
  Assets/Prefabs/Map Objects.prefab
  Assets/Scenes/Basic Enemies.unity
  Assets/Scenes/Basic Enemies.unity.meta
  Assets/Scenes/Boss.unity
  Assets/Scenes/Boss.unity.meta
  Assets/Scenes/Elite Enemies.unity
  Assets/Scenes/Elite Enemies.unity.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/Rest Site.unity
  Assets/Scenes/Rest Site.unity.meta
  Assets/Scenes/Store.unity
  Assets/Scenes/Store.unity.meta
  Assets/Scenes/Treasure.unity
  Assets/Scenes/Treasure.unity.meta
  Assets/Scripts/Map/MapPlayerTracker.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#128 Weapon inventory ammo fix
  Assets/Scenes/Example Room.unity
  Assets/Scripts/Player/WeaponInventory.cs
  Assets/Scripts/Weapons/Data/AssaultRifle.asset
  Assets/Scripts/Weapons/Data/BigBoy.asset
  Assets/Scripts/Weapons/Data/Pistol.asset
  Assets/Scripts/Weapons/Data/Shotgun.asset
  Assets/Scripts/Weapons/Data/Sniper.asset
  Assets/Scripts/Weapons/Data/WeaponData.cs
  Assets/Scripts/Weapons/ProjectileGun/Gun.cs
Labels: bug

#167 Menu and Weapon Quick Change
  Assets/Art/Guns/AR.png.meta
  Assets/Art/Guns/Shotgun.png.meta
  Assets/Scenes/Lighting Room.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Weapons/Data/AssaultRifle.asset
  Assets/Scripts/Weapons/Data/Shotgun.asset
Labels: enhancement
