Repository TigardHighGDC/Augmentation, pull requests merged in 2023-01, with the labels that each got.

#21 Clean Unity files for GitHub Pages
  .clang-format
  .github/workflows/clang-format-check.yml
  Assets/Prefabs.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
  Assets/Scripts.meta
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerMovement.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/AudioManager.asset
  ProjectSettings/ClusterInputManager.asset
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/MemorySettings.asset
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/NetworkManager.asset
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/PresetManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/QualitySettings.asset
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
  ProjectSettings/TimeManager.asset
  ProjectSettings/UnityConnectSettings.asset
  ProjectSettings/VFXManager.asset
  ProjectSettings/VersionControlSettings.asset
  ProjectSettings/XRSettings.asset
  ProjectSettings/boot.config
  Tests/clang_format_check.py
  Tools/clang_format_all.py
Labels: documentation

#18 Gun
  Assets/Prefabs/Bullet.prefab
  Assets/Prefabs/Bullet.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Nate's Scene.unity
  Assets/Scenes/Nate's Scene.unity.meta
  Assets/Scripts/Weapons.meta
  Assets/Scripts/Weapons/Data.meta
  Assets/Scripts/Weapons/Data/Pistol.asset
  Assets/Scripts/Weapons/Data/Pistol.asset.meta
  Assets/Scripts/Weapons/Data/Shotgun.asset
  Assets/Scripts/Weapons/Data/Shotgun.asset.meta
  Assets/Scripts/Weapons/Data/WeaponData.cs
  Assets/Scripts/Weapons/Data/WeaponData.cs.meta
  Assets/Scripts/Weapons/LookAtMouse.cs
  Assets/Scripts/Weapons/LookAtMouse.cs.meta
  Assets/Scripts/Weapons/ProjectileGun.meta
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs.meta
  Assets/Scripts/Weapons/ProjectileGun/Gun.cs
  Assets/Scripts/Weapons/ProjectileGun/Gun.cs.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
Labels: feature

#34 Unity Version Update `2021.3.16f1`
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: high priority, unity

#36 Typo Fixes
  CONTRIBUTING.md
Labels: documentation

#45 Added Title
  README.md
Labels: documentation

#32 Health
  Assets/Scenes/Chris Test Scene.unity
  Assets/Scenes/Chris Test Scene.unity.meta
  Assets/Scripts/EnemyDealDamage.cs
  Assets/Scripts/EnemyDealDamage.cs.meta
  Assets/Scripts/EnemyHealth.cs
  Assets/Scripts/EnemyHealth.cs.meta
  Assets/Scripts/PlayerHealth.cs
  Assets/Scripts/PlayerHealth.cs.meta
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Labels: feature

#49 Sprint 2 Changelog
  Docs/ChangeLog.md
Labels: documentation

#47 Enemy pathfinding
  Assets/Prefabs/A-StarGrid.prefab
  Assets/Prefabs/A-StarGrid.prefab.meta
  Assets/Prefabs/Enemy.prefab
  Assets/Prefabs/Enemy.prefab.meta
  Assets/Prefabs/Wall.prefab
  Assets/Prefabs/Wall.prefab.meta
  Assets/Scenes/Chris' Scene.unity
  Assets/Scenes/Chris' Scene.unity.meta
  ProjectSettings/TagManager.asset
Labels: feature

#51 Collider added to player
  Assets/Prefabs/Player.prefab
Labels: easy

#62 Unity Version Update `2021.3.17f1`
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: high priority, unity
