Repository TigardHighGDC/Augmentation, pull requests merged in 2023-05, with the labels that each got.

#168 Added New Map Assets
  Assets/Art/MapIcons.meta
  Assets/Art/MapIcons/CorruptionRemover.png
  Assets/Art/MapIcons/CorruptionRemover.png.meta
  Assets/Art/MapIcons/EliteEnemyRoom.png
  Assets/Art/MapIcons/EliteEnemyRoom.png.meta
  Assets/Art/MapIcons/EnemyRoom.png
  Assets/Art/MapIcons/EnemyRoom.png.meta
  Assets/Art/MapIcons/ServerBossIcon.png
  Assets/Art/MapIcons/ServerBossIcon.png.meta
  Assets/Art/MapIcons/Shop.png
  Assets/Art/MapIcons/Shop.png.meta
  Assets/Scenes/Corruption Scene.unity
  Assets/Scenes/Corruption Scene.unity.meta
  Assets/Scenes/Level Map.unity
  Assets/Scenes/Rest Site.unity.meta
  Assets/Scenes/Treasure.unity
  Assets/Scenes/Treasure.unity.meta
  Assets/Scripts/Map/MapConfigs/DefaultMapConfig.asset
  Assets/Scripts/Map/MapGenerator.cs
  Assets/Scripts/Map/MapNode.cs
  Assets/Scripts/Map/MapPlayerTracker.cs
  Assets/Scripts/Map/NodeConfigs/Corruption Remover.asset
  Assets/Scripts/Map/NodeConfigs/Corruption Remover.asset.meta
  Assets/Scripts/Map/NodeConfigs/Elite Enemy.asset
  Assets/Scripts/Map/NodeConfigs/Exe Boss.asset
  Assets/Scripts/Map/NodeConfigs/Exe Boss.asset.meta
  Assets/Scripts/Map/NodeConfigs/Executioner Boss.asset
  Assets/Scripts/Map/NodeConfigs/Executioner Boss.asset.meta
  Assets/Scripts/Map/NodeConfigs/Minor Enemy.asset
  Assets/Scripts/Map/NodeConfigs/Mystery.asset
  Assets/Scripts/Map/NodeConfigs/Mystery.asset.meta
  Assets/Scripts/Map/NodeConfigs/Server Boss.asset
  Assets/Scripts/Map/NodeConfigs/Server Boss.asset.meta
  Assets/Scripts/Map/NodeConfigs/Skeleton Boss.asset
  Assets/Scripts/Map/NodeConfigs/Store.asset
  Assets/Scripts/Map/NodeConfigs/Treasure.asset
  Assets/Scripts/Map/NodeType.cs
Labels: enhancement

#178 Bouncing Bullets
  Assets/Scripts/Weapons/Data/AssaultRifle.asset
  Assets/Scripts/Weapons/Data/WeaponData.cs
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Labels: enhancement

#181 Async Scene loader
  Assets/Prefabs/AsyncSceneLoader.prefab
  Assets/Prefabs/AsyncSceneLoader.prefab.meta
  Assets/Scenes/Basic Enemies.unity
  Assets/Scenes/CorruptionWell.unity
  Assets/Scenes/Elite Enemies.unity
  Assets/Scenes/Level Map.unity
  Assets/Scenes/LoadingBar.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/Store.unity
  Assets/Scripts/Environment/Door.cs
  Assets/Scripts/Map/MapPlayerTracker.cs
  Assets/Scripts/Menu.cs
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Scripts/Scene.meta
  Assets/Scripts/Scene/AsyncSceneLoader.cs
  Assets/Scripts/Scene/AsyncSceneLoader.cs.meta
Labels: enhancement

#170 Pause menu
  Assets/Audio/Mixer/Master.mixer
  Assets/Master.mixer
  Assets/Prefabs/PauseMenu.prefab
  Assets/Prefabs/PauseMenu.prefab.meta
  Assets/Scenes/Lighting Room.unity
  Assets/Scripts/PauseMenu.cs
  Assets/Scripts/PauseMenu.cs.meta
  Assets/Scripts/SettingsMenu.cs
  Assets/Scripts/SettingsMenu.cs.meta
  Assets/Scripts/Weapons/LookAtMouse.cs
  Assets/Scripts/Weapons/ProjectileGun/Gun.cs
Labels: question, feature

#187 Dying goes to main menu
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Scripts/Scene/AsyncSceneLoader.cs
Labels: bug, high priority

#188 Map Generation Block Diagram
  Docs/MapBlockDiagram.md
  README.md
Labels: documentation

#195 Updated formatting for `switch` statements
  .clang-format
  Assets/Scripts/Audio/MusicPlayer.cs
  Assets/Scripts/Dialogue/DialogueManager.cs
  Assets/Scripts/Enemies/Boss/BossAnimator.cs
  Assets/Scripts/Enemies/Boss/BossDialogueManager.cs
  Assets/Scripts/Enemies/Boss/BossPhaseManager.cs
  Assets/Scripts/Map/MapNode.cs
  Assets/Scripts/Map/MapPlayerTracker.cs
  Assets/Scripts/Room/EnemySpawner.cs
  Assets/Scripts/UI/OverlayInformationController.cs
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Labels: enhancement, low priority

#184 Player Run Stat Saver
  Assets/HidePlayer.cs
  Assets/HidePlayer.cs.meta
  Assets/Prefabs/Player 1.prefab
  Assets/Prefabs/PlayerStats.prefab
  Assets/Prefabs/PlayerStats.prefab.meta
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/ContinueButton.cs
  Assets/Scripts/ContinueButton.cs.meta
  Assets/Scripts/Map/MapManager.cs
  Assets/Scripts/Menu.cs
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Scripts/Player/PlayerStatManager.cs
  Assets/Scripts/Player/PlayerStatManager.cs.meta
  Assets/Scripts/Player/PlayerStats.cs
  Assets/Scripts/Player/PlayerStats.cs.meta
  Assets/Scripts/Player/WeaponInventory.cs
Labels: feature

#194 Bullet explosion effect
  Assets/Prefabs/Pistol Explosion.prefab
  Assets/Prefabs/Pistol Explosion.prefab.meta
  Assets/Scripts/Weapons/Data/Pistol.asset
  Assets/Scripts/Weapons/Data/WeaponData.cs
  Assets/Scripts/Weapons/ProjectileGun/Bullet.cs
Labels: feature

#196 Added loading bar to map + other map changes
  Assets/Art/MapIcons/LoadingBarIcon.png
  Assets/Art/MapIcons/LoadingBarIcon.png.meta
  Assets/Scripts/Map/MapConfigs/DefaultMapConfig.asset
  Assets/Scripts/Map/MapGenerator.cs
  Assets/Scripts/Map/MapView.cs
  Assets/Scripts/Map/NodeBlueprint.cs
  Assets/Scripts/Map/NodeConfigs/Loading Bar.asset
  Assets/Scripts/Map/NodeConfigs/Loading Bar.asset.meta
Labels: enhancement

#198 Weapon inventory fixes
  Assets/Scripts/Player/WeaponInventory.cs
Labels: bug

#203 Sprint 8 changelog
  Docs/ChangeLog.md
Labels: documentation
